### ISSUE TITLE
Add proper coords to map

### ISSUE THREAD

**Issue by Fia-50** [zDrakon/website#6]
duh

**Comment by zDrakon** [comment]
Tell me how and I will try to do it.

**Comment by Fia-50** [comment]
Don't worry I'll do it, it takes a minute.

**Comment by Fia-50** [comment]
The location they have given us does not exist. I will instead give them a map of 123  6th avenue, NY, which is a nice neighborhood, the map of which looks nice. I will pretend that the map shows the address they gave us.
